### ISSUE TITLE
Authentication failed (Scoold with Docker)

### ISSUE THREAD

**Issue by flavienbwk** [Erudika/scoold#197]
Hi,

I am trying to get started with Scooled but I can't manage to login, always getting : `Authentication failed or was canceled.`

My configuration : 

```
### Minimal configuration ###
# the name of the application
para.app_name = "Scoold"
# the port for Scoold
para.port = 8000
# change this to "production" later
para.env = "development"
# the public-facing URL where Scoold is hosted
para.host_url = "http://localhost:8000"
# the URL of Para - can also be "https://paraio.com"
para.endpoint = "http://para:8080"
# access key for your Para app
para.access_key = "app:scoold"
# secret key for your Para app
para.secret_key = "change_to_long_random_string"
para.app_secret_key = "change_to_long_random_string"
# the email or identifier of the admin user - check Para user object
para.admins = "admin@domain.com"
##############################

####### Authentication #######
para.security.allow_unverified_emails = true
# enable or disable email and password authentication
para.password_auth_enabled = true
# Session cookie name
para.auth_cookie = "scoold-auth"
# Facebook - create your own Facebook app first!
para.fb_app_id = ""
# Google - create your own Google app first!
para.google_client_id = ""
###############################

### Misc. ###
# if false, commenting is allowed after 100+ reputation
para.new_users_can_comment = true
# if true, posts by new users require approval from moderator
para.posts_need_approval = false
# reputation needed for posts to be auto-approved
para.posts_rep_threshold = 100
# needed for geolocation filtering of posts
para.gmaps_api_key = ""
# Enable/disable near me feature (geolocation)
para.nearme_feature_enabled = false
# GA code
para.google_analytics_id = ""
# enables syntax highlighting in posts
para.code_highlighting_enabled = true
# If true, the default space will be accessible by everyone
para.is_default_space_public = true
# If true, users can change their profile pictures
para.avatar_edits_enabled = true
# If true, users can change their names
para.name_edits_enabled = true
# Enable/disable webhooks support
para.webhooks_enabled = true
# Enable/disable wiki style answers
para.wiki_answers_enabled = true
# Comment limits
para.max_comments_per_id = 1000
para.max_comment_length = 1024
# Post body limit (characters)
para.max_post_length = 20000
# Tags per post limit, must be < 100
para.max_tags_per_post = 20
# Sets the default tag for new questions
para.default_question_tag = "" # "question"
# Enable/disable numeric pagination (< 1 2 3...N >)
para.numeric_pagination_enabled = false
# Selects the default language to load on startup, defaults to 'en'
para.default_language_code = ""

# styling
para.inline_css = ".navbar-color { color: #292929; }"
```

My compose file (Dockerfiles are the same than the official ones) : 

```
version: '3.2'

services:
   para:
     build:
      context: .
      dockerfile: para.Dockerfile
     image: erudikaltd/para
     ports:
       - "8080:8080"
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: volume
         source: paraLib
         target: /para/lib
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     restart: always
     env_file: para.env

   scoold:
     depends_on:
       - para
     build:
      context: .
      dockerfile: Dockerfile
     image: erudikaltd/scoold
     ports:
       - "8000:8000"
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     restart: always
     env_file: scoold.env

volumes:
  paraData:
  paraLib:
```

Thank you for your help !
