### ISSUE TITLE
para LDAP config is not picked up correctly

### ISSUE THREAD

**Issue by ensecoz** [Erudika/scoold#67]
I'm setting up server like this:

```
scoold server
  - application.conf
    - para.security.ldap.server_url = "ldap://test.com"
    - (...other)
para server
  - application.conf
```

at first try, everything is working but after adjust some of the configuration. I am not sure what is the root cause. now suddenly there is an error cannot authenticate with LDAP server **localhost:8389** (which is the default)

my workaround is:

I have to also put the config inside the para (application.conf) too and now it is working again.

```
scoold server
  - application.conf
    - para.security.ldap.server_url = "ldap://test.com"
    - (...other)
para server
  - application.conf
    - para.security.ldap.server_url = "ldap://test.com"
    - (...other)
```

**Comment by albogdano** [comment]
Are you mounting the config file with `-v application.conf:applciation.conf`? 
Also, have you created a separate app for Scoold in Para? 

The workaround you describe is setting LDAP configuration for the root app in Para, called "app:para".

**Comment by ensecoz** [comment]
yes, i have separated application.conf for both scoold and para

docker-compose.yml
```
 para:
     volumes:
       - type: volume
         source: paraData
         target: /para/data
       - type: bind
         source: ./para-application.conf
         target: /para/application.conf
     ...
   scoold:
     depends_on:
       - para
     volumes:
       - type: bind
         source: ./scoold-application.conf
         target: /scoold/application.conf
     ...
```

scoolid-application.conf
```
para.app_name = "my-scoold"
para.port = 8000
para.env = "production"
para.host_url = "https://myscoold"
para.endpoint = "http://para:8080"
para.access_key = "app:my-para"
...
```

para-application.conf
```
para.app_name = "my-para"
para.env = "production"
...
```
